"""
general_agent.py — Handles questions that the router classifies as GENERAL
(greetings, small talk, off-topic queries with no SQL needed).
"""

# ── MODULE TAG: General Conversational Agent ──
from typing import Optional
from core.config.logger import get_logger
from security.guardrails import has_write_intent, READ_ONLY_REFUSAL
from prompts.loader import prompt_loader
from core.llm.llm_client import ask_llm, ask_llm_async

log = get_logger(__name__)

_DB_META_KEYWORDS = (
    "table", "tables", "database", "databases", "schema", "column", "columns",
    "record", "records", "how many", "list all", "show all", "what data",
    "what tables", "count", "rows",
    "picklist", "picklists", "inventory", "stock", "location", "locations",
    "grn", "item", "items", "warehouse", "warehouses", "sku", "putaway",
    "sulocation", "fgtransaction", "vendor",
)


def _check_general_chat_interceptors(
    question: str,
    has_write: bool = False,
    write_reason: Optional[str] = None,
) -> str | None:
    """Check if the question asks to modify data or needs a standard quick response.

    Args:
        question (str): The user's question text.
        has_write (bool, optional): True if the question attempts database edits. Defaults to False.
        write_reason (Optional[str], optional): Explanation string if write attempt was detected. Defaults to None.

    Returns:
        str | None: Refusal message if blocked, quick answer string if matched, or None to ask the AI model.
    """
    q_lower = question.lower()

    if not has_write:
        has_write, write_reason = has_write_intent(question)
    if has_write:
        log.warning(f"GeneralAgent: Write/CRUD intent intercepted: '{question}'")
        return write_reason or READ_ONLY_REFUSAL

    is_meta_explanation = any(phrase in q_lower for phrase in ["how do you", "how you", "how does", "explain how", "can you fetch", "can you query"])

    if is_meta_explanation and any(kw in q_lower for kw in ["fetch", "query", "get data", "get the data"]):
        return "I fetch data using a SQL query generated by the LLM."

    if not is_meta_explanation and any(kw in q_lower for kw in _DB_META_KEYWORDS):
        return (
            "It looks like you're asking about the database. Let me check that for you — "
            "could you rephrase your question? For example: 'List all tables' or "
            "'How many picklists are completed?'"
        )

    return None


def handle_general_chat(
    question: str,
    has_write: bool = False,
    write_reason: Optional[str] = None,
) -> str:
    """Respond to greetings and general conversation synchronously.

    Args:
        question (str): The user's question text.
        has_write (bool, optional): True if write attempt detected. Defaults to False.
        write_reason (Optional[str], optional): Refusal explanation string. Defaults to None.

    Returns:
        str: The chat response text generated by the AI or quick rules.
    """
    intercepted = _check_general_chat_interceptors(question, has_write, write_reason)
    if intercepted is not None:
        return intercepted

    general_desc = prompt_loader.get_agent_config("GENERAL").get("description", "")
    try:
        return ask_llm(general_desc, question)
    except Exception as e:
        log.error(f"GeneralAgent sync execution error: {e}")
        from core.llm.llm_client import format_llm_api_error
        return format_llm_api_error(e)


async def handle_general_chat_async(
    question: str,
    has_write: bool = False,
    write_reason: Optional[str] = None,
) -> str:
    """Respond to greetings and general conversation asynchronously.

    Args:
        question (str): The user's question text.
        has_write (bool, optional): True if write attempt detected. Defaults to False.
        write_reason (Optional[str], optional): Refusal explanation string. Defaults to None.

    Returns:
        str: The chat response text generated by the AI or quick rules.
    """
    intercepted = _check_general_chat_interceptors(question, has_write, write_reason)
    if intercepted is not None:
        return intercepted

    general_desc = prompt_loader.get_agent_config("GENERAL").get("description", "")
    try:
        return await ask_llm_async(general_desc, question)
    except Exception as e:
        log.error(f"GeneralAgent async execution error: {e}")
        from core.llm.llm_client import format_llm_api_error
        return format_llm_api_error(e)

