"""
general_chat.py — Handles questions that the router classifies as GENERAL
(greetings, small talk, off-topic queries with no SQL needed).

Also guards against cases where the router misclassifies a DB-related
question as GENERAL, returning a helpful nudge instead of hallucinating.
"""


# ── MODULE TAG: General Conversational Agent ──
# ── STITCHGUARD LAYER: L2 (Safe General Query Interceptors) ──
from config.logger import get_logger

log = get_logger(__name__)

# ── CONVERSATIONAL KEYWORD SANITIZATION ──────────────────────────────────────────
# If any of these words appear in a "GENERAL" question, the router likely
# made a mistake — return a safe redirect instead of a hallucinated answer.
_DB_META_KEYWORDS = (
    "table", "tables", "database", "databases", "schema", "column", "columns",
    "record", "records", "how many", "list all", "show all", "what data",
    "what tables", "count", "rows",
)


# ── CONVERSATIONAL EXECUTION ENGINE ──────────────────────────────────────────────
def handle_general_chat(question: str) -> str:

    """
    Return a friendly reply for greetings and off-topic questions.

    If the question contains DB-related keywords, assume the router misfired
    and return a safe message instead of letting the LLM make up DB facts.

    Args:
        question: The user's question classified as GENERAL by the router.

    Returns:
        A plain-text reply string.
    """
    q_lower = question.lower()
    is_meta_explanation = any(phrase in q_lower for phrase in ["how do you", "how you", "how does", "explain how", "can you fetch", "can you query"])
    
    if is_meta_explanation and any(kw in q_lower for kw in ["fetch", "query", "get data", "get the data"]):
        return "I fetch data using a SQL query generated by the LLM."

    if not is_meta_explanation and any(kw in q_lower for kw in _DB_META_KEYWORDS):
        return (
            "It looks like you're asking about the database. Let me check that for you — "
            "could you rephrase your question? For example: 'List all tables' or "
            "'How many employees are there?'"
        )

    # Import here to avoid circular dependency at module load time
    from prompts.prompt_loader import prompt_loader
    from llm.llm_client import ask_llm

    general_desc = prompt_loader.get_agent_config("GENERAL").get("description", "")
    return ask_llm(general_desc, question)
