[theme]
base = "light"
primaryColor = "#d7474aff"
backgroundColor = "#ffffffff"
secondaryBackgroundColor = "#ffffffff"
textColor = "#18181b"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
